(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[31634],{20563:function(e,n,r){(window.__NEXT_P=window.__NEXT_P||[]).push(["/quizzes/asynchronous-javascript/promises-and-then-catch/how-does-error-handling-work-in-promise-chains",function(){return r(53022)}])},16833:function(e,n,r){"use strict";r.d(n,{Z:function(){return a}});var t=r(85893),o=r(67294),s=e=>{let{adClient:n="ca-pub-7544108447932228",adSlot:r="6753219060",className:s}=e,a=(0,o.useRef)(null),c=(0,o.useRef)(!1),[i,d]=(0,o.useState)(!1);return((0,o.useEffect)(()=>(d(!0),()=>{let e=document.getElementById("__next");e&&e.removeAttribute("style")}),[]),(0,o.useEffect)(()=>{if(i){if(document.querySelector('script[src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"]'))a.current&&!c.current&&((window.adsbygoogle=window.adsbygoogle||[]).push({}),c.current=!0);else{let e=document.createElement("script");e.src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7544108447932228",e.async=!0,e.crossOrigin="anonymous",document.body.appendChild(e),e.onload=()=>{a.current&&!c.current&&((window.adsbygoogle=window.adsbygoogle||[]).push({}),c.current=!0)}}}},[i]),i)?(0,t.jsx)("ins",{ref:a,className:"adsbygoogle ".concat(s),style:{display:"block"},"data-ad-client":n,"data-ad-slot":r}):null};function a(e){return class extends o.Component{componentDidMount(){console.log("Wrapped Component")}render(){return(0,t.jsx)(t.Fragment,{children:(0,t.jsxs)("div",{className:" md:grid grid-cols-[20%_60%_20%]  w-[95%] ",children:[(0,t.jsx)("div",{children:(0,t.jsx)(s,{adSlot:"6753219060",className:"h-[100px] md:h-full"})}),(0,t.jsx)("div",{children:(0,t.jsx)(e,{...this.props})}),(0,t.jsx)("div",{children:(0,t.jsx)(s,{adSlot:"2871546317",className:"h-[300px] md:h-full"})})]})})}constructor(e){super(e)}}}},53022:function(e,n,r){"use strict";r.r(n),r.d(n,{__N_SSG:function(){return c}});var t=r(85893),o=r(1475),s=r(25190),a=r(16833),c=!0;n.default=(0,s.Z)((0,a.Z)(()=>(0,t.jsxs)(t.Fragment,{children:[(0,t.jsx)("h1",{className:"text-2xl dark:text-white text-center",children:"Promises & then/catch"}),(0,t.jsx)("div",{className:"flex justify-center w-full p-5 md:p-0 pt-0",children:(0,t.jsx)(o.Y3,{activeQuestionIndex:8,totalQuestions:21,index:8,question:"How does error handling work in Promise chains?",options:["Each then() must handle its own errors","Errors propagate down until caught","Errors stop the chain immediately","Errors are ignored by default"],code:"promise\n  .then(value => {\n    throw new Error('Something went wrong');\n  })\n  .then(value => console.log('Never called'))\n  .catch(error => console.error(error));",nextQuestionPath:"how-does-this-error-handling-compare-to-catch",correctAnswer:2,explanation:"Errors in Promise chains propagate until caught by a catch() handler: 1) Any error thrown in a then() handler becomes a rejection, 2) Rejections skip subsequent then() handlers until a catch() is found, 3) catch() handlers can recover from errors by returning a value, 4) The chain can continue after catch() if needed, 5) Similar to try/catch but for asynchronous operations, 6) Enables centralized error handling for entire chains.",id:520,quizId:24},8)})]})))}},function(e){e.O(0,[41966,25675,82893,92888,49774,40179],function(){return e(e.s=20563)}),_N_E=e.O()}]);